#
#	File:		Makefile
#
#	Contains:	xxx put contents here xxx
#
#	Written by:	David Hankinson
#
#	Copyright:	© 1994 by Catapult Entertainment, Inc., all rights reserved.
#
#	Change History (most recent first):
#
#		 <1>	 7/15/94	dwh		first checked in
#
#	To Do:
#

include ../../UNIX/Makefile.config

INCOPTS=-I../../SegaOS/Interfaces \
	-I../../SegaOS/Graphics \
	-I../../SegaOS/OSCore \
	-I../../SegaOS/Shell \
	-I../../SegaOS/Misc \
	-I../../Comm

OBJS =	PreformedMessage.o

all: $(OBJS)

clean::
	$(RM) $(OBJS)
